language: python
python:
- '2.7'
install:
- pip install -U setuptools
script: true
after_success: python build.py --command="sdist bdist_wheel"
deploy:
  provider: releases
  api_key:
    secure: kUJZ/Mgy+pKAYCsxv3j2OTDQ3sO1/XWR1ejr6Nq7kMIkQ3ad/u18oxg0mqVWbfnEylbAozPeGrCxqecEGcnaDE3p4bb0RZSxzvFI5PLbGq0mzqfL3lchOrD1tOH4FIPrFewypUj+hc8dU1GhU2xpWKiHvq21I9OfEmXTTbbc48Rw7gkF1sdS+/z6aUHsUXMIm5Bnn2DbufjI8vF3wV2thqIzOKAz3qNqkEE0VHLFnkV2PuG2JG/AgIHMCsT2NENzQCuXBMuigCb2U8VFLyPR6uRJbsZGcw60+TznBJpzfR0TqV6laGH0MQBjxgVks1plQvObcLRkWq0Qg8mequiwS7x2vrWMXxLpCwHE75SlgE0tZRpRBLsOLupWAdB8saJ4Et9aBgvuVMeWLxmm6ORxTDBnVZdm26An+nvr2wD9qG7ZHSZmcK/q35Ds6Z1Tsfhn0K9mb+LajktXGssQ33/wvKHryH8zJpa9lTPXeu+dm/OTAvViGSKmygb5K+8JzWukYObGttYUExK7tp2oYhgXCoX+7hdoF/+pC8wG95naU6Jxy9KgCiK52S6pKdWq3we5+D9IfjW2XsM3a0mKjDQof7jciELcZojp8SzegGcoMr3zO7vQEkmCplJ2uLAbyolYxme3MaLv2p0CPXv4QPrq7rJaIMME56UIC/hnx3UhhIM=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-anidb-tmdb-show*"
  - "dist/oem_database_anidb_tmdb_show*"
  on:
    repo: OpenEntityMap/oem-database-anidb-tmdb-show
    tags: true
